name: Compile and Package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MinGW
          choco install mingw --version 9.3.0 --params "/threads:posix /exception:sjlj" --allow-downgrade --side-by-side
      - name: Compile Main.c
        run: |
          gcc -v
          gcc -o main.exe main.c
      - name: Package Main.exe
        run: 7z a main.7z main.exe
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.1'
          release_name: 'Release v1.0.1'
          draft: false
          prerelease: false
      - name: Upload Main.7z
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: main.7z
          asset_name: main.7z
          asset_content_type: application/x-7z-compressed
