   name: Build Windows
   on: 
    push:
      paths:
      - '**.md'
   jobs:
     build:
       runs-on: windows-latest
       steps:
         - uses: actions/checkout@v2
         - name: Setup Mingw
           run: |
             choco install mingw
         - name: Build with Mingw
           run: |
             mingw32-make -f Makefile
             mingw64-make -f Makefile
         - name: Upload release
           uses: actions/upload-release-asset@v1
           with:
             upload_url: ${{ github.event.release.upload_url }}
             asset_path: main.exe
             asset_name: main-${{ github.ref }}.exe
             asset_content_type: application/octet-stream
