name: Compile and Package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MinGW
        uses: actions/setup-mingw@v1
        with:
          version: '9.3.0'
      - name: Compile Main.c
        run: gcc -o main.exe main.c
      - name: Package Main.exe
        run: 7z a main.7z main.exe
      - name: Upload Main.7z
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: main.7z
          asset_name: main.7z
          asset_content_type: application/x-7z-compressed
